config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  
  get 'index', to: 'pages#index'
  get 'about', to: 'pages#about'

  get 'posts', to: 'posts#index'
  get 'show_post/:id', to: 'posts#show', as: 'show_post'
  get 'new_post' => 'posts#new'
  post 'create_post' => 'posts#create'
  get 'edit_post/:id', to: 'posts#edit', as: 'edit_post'
  patch 'update_post/:id', to: 'posts#update', as: 'update_post'
  delete 'delete_post/:id', to: 'posts#delete', as: 'delete_post'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, :content, :presence => true
    validates :title, :content, :length => { :minimum => 4 }
    validates :title, :content, :uniqueness => { :message => "already taken!!" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def index
    end
    
    def about
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to posts_path, :notice => "Post created!!"
        else
            render 'new'
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
            redirect_to posts_path, :notice => "Post edited!!"
        else
            render 'edit'
        end
    end

    def delete
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path, :notice => "Post deleted!!"
    end

    private def post_params
        params.require(:post).permit(:title, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<%= render 'partials/header' %>

<div class="notes_wrapper">
  <%= yield %>
</div>

<script src="/js/dist/bundle.js"></script>
</body>
</html>

app/views/pages/about.html.erb
<% content_for :title, "About" %>

<div class="welcome">
  <%= image_tag "dutch.gif" %>
</div>

app/views/pages/index.html.erb
<% content_for :title, "Home" %>

<div class="welcome">
  <%= image_tag "dutch.gif" %>
</div>

app/views/partials/_emssg.html.erb
<div class="flash">
  <span class="flash_mssg"><%= mssg %></span>
  <span class="flash_icon">
    <i class="material-icons">clear</i>
  </span>
</div>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Rails Notes App</title>
    <!-- <link rel="icon" href="/images/favicon.png" type="image/png"> -->
    <%= favicon_link_tag 'favicon.ico' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if flash.any? %>
      <%= render 'partials/emssg', mssg: flash[:notice] %>
    <% end %>

    <div class="header_loggedin">
      <div class="left">
        <%= link_to "Home", root_path %>
        <%= link_to "About", about_path %>
        <%= link_to "Notes", posts_path %>
        <%= link_to "Create Note", new_post_path %>
      </div>
    </div>

app/views/posts/edit.html.erb
<% content_for :title, "Edit Note" %>

<div class="edit">

  <div class="edit_info">
    <%= image_tag  "ruby-red.png", class: "edit_img", alt: "Your avatar" %>
    <span>Edit Note</span>
  </div>

  <%= form_for @post, url: { action: 'update' } do |f| %>

    <% if @post.errors.any? %>
      <%= render 'partials/emssg', mssg: @post.errors.full_messages[0] %>
    <% end %>

    <div class="eu_div">
      <span class='edit_span'>Title</span>
      <%= f.text_field :title, class: "e_username", placeholder: 'Title..', autofocus: true, spellcheck:false, autocomplete: false %>
    </div>
    <div class="eb_div">
      <span class='edit_span'>Content</span>
      <%= f.text_area :content, placeholder: "Content..", autofocus: true, class: "e_bio", spellcheck:false, autocomplete: false %>
    </div>
    <div class="eb_btns">
      <%= f.submit "Update Note" %>
    </div>

  <% end %>

</div>

app/views/posts/index.html.erb
<% content_for :title, "Notes" %>

<div class="home">

  <div class="home_info">
    <span><%= @posts.length %> Notes</span>
    <%= link_to "Create Note", new_post_path, class: "pri_btn" %>
  </div>

  <% unless @posts.empty? %>
    <% @posts.each do |el| %>
      <div class="note">
        <div class="note_header common_header">
          <%= image_tag "ruby-red.png" %>
          <div class="note_h_left">
            <span class="note_username">You..</span>
            <span class='note_time'><%= el.created_at %></span>
          </div>
        </div>
        <div class="note_title">
          <span><%= el.title %></span>
        </div>
        <div class="note_content">
          <span><%= el.content %></span>
        </div>
        <div class="note_actions">
          <%= link_to "Edit", edit_post_path(el.id), class: "sec_btn" %>
          <%=
            link_to "Delete",
            delete_post_path(el.id),
            class: "sec_btn",
            :data => { :confirm => "Are you sure??" },
            :method => :delete
          %>
          <%= link_to "View", show_post_path(el.id), class: "pri_btn" %>
        </div>
      </div>
    <% end %>
  <% end %>

  <% if @posts.empty? %>
    <div class='home_last_mssg'>
      <%= image_tag "large.jpg" %>
      <span>No notes for you. Go ahead and create one!!</span>
    </div>
  <% end %>

  <% unless @posts.empty? %>
    <div class="page_end">
      <span>Looks like you've reached the end</span>
    </div>
  <% end %>

</div>

app/views/posts/new.html.erb
<% content_for :title, "New Note" %>

<div class="edit">

  <div class="edit_info">
    <%= image_tag  "ruby-red.png", class: "edit_img", alt: "Your avatar" %>
    <span>Create Note</span>
  </div>

  <%= form_for @post, url: { action: 'create' } do |f| %>

    <% if @post.errors.any? %>
      <%= render 'partials/emssg', mssg: @post.errors.full_messages[0] %>
    <% end %>

    <div class="eu_div">
      <span class='edit_span'>Title</span>
      <%= f.text_field :title, class: "e_username", placeholder: 'Title..', autofocus: true, spellcheck:false, autocomplete: false %>
    </div>
    <div class="eb_div">
      <span class='edit_span'>Content</span>
      <%= f.text_area :content, placeholder: "Content..", autofocus: true, class: "e_bio", spellcheck:false, autocomplete: false %>
    </div>
    <div class="eb_btns">
      <%= f.submit "Create Note" %>
    </div>

  <% end %>

</div>

app/views/posts/show.html.erb
<% content_for :title, "View Note" %>

<div class="notes_wrapper">
  <div class="home">

    <div class="blog">
      <div class="blog_c">
        <span class="blog_title"><%= @post.title %></span>
        <span class="blog_content"><%= @post.content %></span>
      </div>
      <div class="blog_actions">
        <%= link_to "Edit", edit_post_path(@post.id), class: "sec_btn" %>
        <%=
          link_to "Delete",
          delete_post_path(@post.id),
          class: "sec_btn blog_dlt",
          :data => { :confirm => "Are you sure??" },
          :method => :delete
        %>
        <%= link_to "Back", posts_path, class: 'pri_btn' %>
      </div>
    </div>

  </div>
</div>